FROM python:3.8
WORKDIR /opt/yanr
COPY . .
RUN pip install --no-cache-dir -r ./requirements/prod-deploy.txt
ENV PYTHONPATH="${PYTHONPATH}:/opt/yanr"
RUN python -m dvc pull yanr/workflow/dvc/word2vec/data/external/coins.json.dvc
RUN python -m nltk.downloader punkt
RUN python -m nltk.downloader stopwords
RUN python -m nltk.downloader wordnet
RUN python -m nltk.downloader omw-1.4